In [1]:
4+5


9

In [4]:
!pip install numpy 

You should consider upgrading via the 'c:\users\91826\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [5]:
import numpy as np

In [7]:
a= np.array([5,7,8])
a

array([5, 7, 8])

In [8]:
a.shape    #tells dimension

(3,)

In [9]:
b = np.array([[5,7,8], [7,3,4]])
b

array([[5, 7, 8],
       [7, 3, 4]])

In [13]:
# 3d matrix
d=np.array([[[4,8,7],[3,1,5],[6,9,13]],[[41,81,71],[31,11,51],[61,91,131]]])
d

array([[[  4,   8,   7],
        [  3,   1,   5],
        [  6,   9,  13]],

       [[ 41,  81,  71],
        [ 31,  11,  51],
        [ 61,  91, 131]]])

In [26]:
d.shape

(2, 3, 3)

In [14]:

c = np.array([[3,8,4], [9,3,5],[11,15,17],[19,31,8]])
c

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [15]:
c[1,0]

9

In [16]:
d[1,0,2]

71

In [19]:
c[0:4:1,2]

array([ 4,  5, 17,  8])

In [21]:
c[:,1:2]

array([[ 8],
       [ 3],
       [15],
       [31]])

In [22]:
d[:2,-2:,:1]

array([[[ 3],
        [ 6]],

       [[31],
        [61]]])

In [25]:
m = np.array([
    [[4,41], [8,81], [7,71]],
    [[3,31], [1,11], [5,51]],
    [[6,91], [9,91], [13,131]]
    ])
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  91],
        [  9,  91],
        [ 13, 131]]])

In [27]:
m.shape

(3, 3, 2)

In [23]:
d[-1:,-2:,:]

array([[[ 31,  11,  51],
        [ 61,  91, 131]]])

In [28]:
c[0,0] =505
c

array([[505,   8,   4],
       [  9,   3,   5],
       [ 11,  15,  17],
       [ 19,  31,   8]])

In [29]:
c[1,:]=([4,5,6])
c

array([[505,   8,   4],
       [  4,   5,   6],
       [ 11,  15,  17],
       [ 19,  31,   8]])

In [32]:
c[:,1]=[65,7,8,2]
c

array([[505,  65,   4],
       [  4,   7,   6],
       [ 11,   8,  17],
       [ 19,   2,   8]])

In [34]:
c+3

array([[508,  68,   7],
       [  7,  10,   9],
       [ 14,  11,  20],
       [ 22,   5,  11]])

In [35]:
c[4:,:] = [3,4,5]
c

array([[505,  65,   4],
       [  4,   7,   6],
       [ 11,   8,  17],
       [ 19,   2,   8]])

In [36]:
# insert row
np.append(c, [[1,1,1]], axis=0)

array([[505,  65,   4],
       [  4,   7,   6],
       [ 11,   8,  17],
       [ 19,   2,   8],
       [  1,   1,   1]])

In [45]:
# column insert
np.append(c, [[1],[1],[0],[1]], axis=1)

array([[505,  65,   4,   1],
       [  4,   7,   6,   1],
       [ 11,   8,  17,   0],
       [ 19,   2,   8,   1]])

In [48]:
# column delete
np.delete(c,(1,2),axis=1) 

array([[505],
       [  4],
       [ 11],
       [ 19]])

In [2]:
%pip install opencv-python

You should consider upgrading via the 'c:\users\91826\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [3]:
%pip install scikit-image

You should consider upgrading via the 'c:\users\91826\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [7]:
import numpy as np

In [8]:
np.arange(1,11,1) #will give list of  no's from 1 to 10
#it will form numpy array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
np.ones([4,5], dtype = int) #generates matrix of 4*5 of 1's
# dtype is datatype of elements


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
k=np.ones([4,5])
k

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
k.dtype

dtype('float64')

In [26]:
k.astype(int)  #ussed to convert datatype

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.randint(1,100,2)

array([23, 90])

In [33]:
np.random.seed(5000)
np.random.randint(1,100,[3,5])

array([[28, 67, 98,  2, 30],
       [ 3, 15,  4, 97, 60],
       [27, 68, 47,  4, 65]])

In [35]:
r= np.random.rand(3,4)
r

array([[0.94523217, 0.78794482, 0.14000959, 0.57047153],
       [0.85473748, 0.1713865 , 0.24605194, 0.10209443],
       [0.07659559, 0.37296226, 0.38235538, 0.33108826]])

In [36]:
np.random.randn(3,4)  #include both +ve AND -VE NO'S

array([[ 0.86766531, -0.34190492,  0.52449497,  0.1697441 ],
       [-0.71049565, -1.19071655,  0.17340345, -0.67895379],
       [-0.18956986, -0.72538966, -1.68081151,  0.10756353]])

In [37]:
import random

In [ ]:
np.random.choice()

In [40]:
np.loadtxt('data.txt', dtype ='str')

array([['this', 'is', 'my', 'new', 'file'],
       ['here', 'we', 'got', 'some', 'data']], dtype='<U4')

In [46]:
np.loadtxt('data1.txt',delimiter=',')

array([[45., 67., 78., 98.],
       [23., 33.,  1., 88.],
       [ 1.,  4.,  5.,  6.]])

In [49]:
a=np.random.randint(10,1000, [3,5])
a

array([[572, 663, 157, 104, 730],
       [914, 321,  59, 885, 283],
       [925, 244, 501, 646, 483]])

In [50]:
np.savetxt('data3.txt', a, delimiter = '|', fmt= '%d')

In [56]:
sum(sum(a))  # sum for 2-dimensional

7487

In [52]:
a.sum(axis=0) #for column wise sum

array([2411, 1228,  717, 1635, 1496])

In [53]:
a.sum(axis=1)  #for row-wise sum

array([2226, 2462, 2799])

In [54]:
a.max(axis=1)  #maximum value in a row

array([730, 914, 925])

In [55]:
a.argmax(axis=1) #reurns index of max value in a row

array([4, 0, 0], dtype=int64)

In [57]:
a.flatten()

array([572, 663, 157, 104, 730, 914, 321,  59, 885, 283, 925, 244, 501,
       646, 483])

In [59]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [61]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [62]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [65]:
np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
np.random.rand(1)

array([0.21650183])

In [71]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [73]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [76]:
a[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [77]:
a[-2,-1]

20

In [81]:
a[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [85]:
a[:,-3:].sum(axis=1)

array([12, 27, 42, 57, 72])

In [86]:
a[-1,:].std()  #standard deviation

1.4142135623730951